apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot-gateway
  template:
    metadata:
      labels:
        app: bot-gateway
    spec:
      containers:
        - name: bot-gateway
          image: ghcr.io/xxxaosss/bot-gateway:latest
          envFrom:
            - secretRef:
                name: bot-secrets
          env:
            - name: BACKEND_URL
              value: "http://backend:8000"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
      imagePullSecrets:
        - name: ghcr-secret # убери, если пакет публичный
